export default {
    "translation": {
        "Dashboard": "Dashboard",
        "Devices": "Devices",
        "Settings": "Settings",
        "Admin": "Admin",
        "Tenants": "Tenants",
        "User": "User",
        "Devices": "Devices",
        "TotalDevices": "Total Devices",
        "WaterMeters": "Water Meters",
        "ElectricityMeters": "Electricity Meters",
        "OfflineDevices": "Offline Devices",
        "DeviceName": "Device Name",
        "ClientName": "Client Name",
        "Status": "Status",
        "DateLastReadingWater": "Date Last Reading Water",
        "LastReadingWaterLT": "Last Reading Water (Liters)",
        "DateLastReadingElectricity": "Date Last Reading Electricity",
        "LastReadingElectricitykWH": 'Last Reading Electricity (kWh)',
        "Status": "Status",
        "Water": "Water",
        "Electricity": 'Electricity',
        "Home": "Home",
        "Profile": "Profile",
        "Logout": "Logout",
        "All": "All",
        "Offline": "Offline",
        "Online": "Online",
        "Security": "Security",
        "MyDetails": 'My Details',
        "FirstName": "First Name",
        "LastName": "Last Name",
        "Email": "Email",
        "MyPhoneNumber": "My Phone Number",
        "CompanyDetails": 'Company details',
        "CompanyAddress": "Company Address",
        "Country": "Country",
        "State": "State",
        "City": "City",
        "State": "State",
        "Address": "Adress",
        "Discard": "Discard",
        "SaveChanges": "SaveChanges",
        "ChangePassword": 'Change Password',
        "CurrentPassword": "Current Password",
        "NewPassword": "New Password",
        "ConfirmNewPassword": "Confirm New Password",
        "PasswordDeviceRenaming": 'Password Device Renaming',
        "Password": "Password",
        "LoginHistory": "Login History",
        "YourRecentLoginActivity": "Your recent login activity",
        "Create": "Create",
        "TenantName": "Tenant Name",
        "CompanyEmail": "Company Email",
        "CompanyPhoneNumber": "Company Phone Number",
        "CompanyName": "Company Name",
        "Address": "Address",
        "PhoneNumber": "Phone Number",
        "VATID": "VAT ID",
        "TotalDevices": "Total Devices",
        "Users": 'Users',
        "UserName": "User Name",
        "UserEmail": "User Email",
        "Phone Number": "Phone Number",
        "Tenants": "Tenant(s)",
        "Tenant": "Tenants",
        "Company": 'Company',
        "PermissionProfile": "Permission Profile",
        "Devices": "Devices",
        "DeviceName": "Device Name",
        "ClientName": "Client Name",
        "SignIn": "Sign in",
        "EmailAddr": "Email Address",
        "ForgotPass": "Forgot Password?",
        "ResetPass": "Reset Password",
        "UpdatePass": "Update Password",
        "SendResetLink": "Send Reset Link",
        "ConfirmPass": "Confirm Password",
        "TodayPowerUsage": "Today's Power Usage",
        "CurrentWeekUsage": "Current Week Usage",
        "Website": "Website",
        "ZipCode": "ZipCode"
    }
}
