export const USER_PERMISSIONS = 'USER_PERMISSIONS';
export const USER_UPDATE = 'USER_UPDATE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const LOGIN_HISTORY = 'LOGIN_HISTORY';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
