export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICE = 'GET_DEVICE';
export const DASHBOARD_DEVICES = 'DASHBOARD_DEVICES';
export const DEVICE_READING = 'DEVICE_READING';
export const GET_DASHBOARD_DEVICES = 'GET_DASHBOARD_DEVICES';